---
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'debian/**'
      - 'doc/**'
    branches:
      - master

permissions:
  contents: read #  to fetch code (actions/checkout)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            meson \
            ccache

      - id: cache-ccache
        uses: hendrikmuhs/ccache-action@v1

      - name: Configure
        run: |
          meson setup \
            -Dauto_features=enabled \
            -Dapreq2=disabled \
            -Dxios=disabled \
            -Ddocumentation=disabled \
            -Dwrap_mode=nofallback \
            --force-fallback-for=libcm4all-http \
            output

      - name: Build
        run: ninja -C output -v

      - name: Unit Tests
        run: meson test -C output

      - name: Dump Unit Test Log
        if: ${{ failure() }}
        continue-on-error: true
        run: cat output/meson-logs/testlog.txt
